version: 1
disable_existing_loggers: true
loggers:
  superdesk:
    level: WARN
  superdesk.ws:
    level: WARN
  superdesk.websockets_comms:
    level: WARN
  flask.ext.cors:
    level: ERROR
  elasticsearch:
    level: WARN
  ldap:
    level: WARN
  worker:
    level: WARN
